name: Local Docker Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: 'True'
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build and start containers
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Wait for services to start
      run: sleep 20

    - name: Check if Django app is responding
      run: |
        curl -f http://localhost:8000 || (docker-compose logs && exit 1)

    - name: Tear down containers
      if: always()
      run: docker-compose down -v
